// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOI1DqYP97_uvK-mFsZBHzpa34vV5nEk',
    appId: '1:298051748692:web:ac4677ae34eb15d47fbec1',
    messagingSenderId: '298051748692',
    projectId: 'minimalistic-social-app',
    authDomain: 'minimalistic-social-app.firebaseapp.com',
    storageBucket: 'minimalistic-social-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCIXWXwN4M_jn0pmfmG_qXQ6hQ33Ann8',
    appId: '1:298051748692:android:d75fa1d6f4e037457fbec1',
    messagingSenderId: '298051748692',
    projectId: 'minimalistic-social-app',
    storageBucket: 'minimalistic-social-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEu-YrlpwsqlG4VzWZr7UeMl14oAWU464',
    appId: '1:298051748692:ios:7afd92f8b873cd487fbec1',
    messagingSenderId: '298051748692',
    projectId: 'minimalistic-social-app',
    storageBucket: 'minimalistic-social-app.firebasestorage.app',
    iosBundleId: 'com.example.minimalisticSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEu-YrlpwsqlG4VzWZr7UeMl14oAWU464',
    appId: '1:298051748692:ios:7afd92f8b873cd487fbec1',
    messagingSenderId: '298051748692',
    projectId: 'minimalistic-social-app',
    storageBucket: 'minimalistic-social-app.firebasestorage.app',
    iosBundleId: 'com.example.minimalisticSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOI1DqYP97_uvK-mFsZBHzpa34vV5nEk',
    appId: '1:298051748692:web:ac4677ae34eb15d47fbec1',
    messagingSenderId: '298051748692',
    projectId: 'minimalistic-social-app',
    authDomain: 'minimalistic-social-app.firebaseapp.com',
    storageBucket: 'minimalistic-social-app.firebasestorage.app',
  );
}
