// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWlZmdSGsScvxqKz6YHpi24nXBExCAHFw',
    appId: '1:755431663302:web:b2c43ef64ff28b3d3559c7',
    messagingSenderId: '755431663302',
    projectId: 'internspirit-hackathon',
    authDomain: 'internspirit-hackathon.firebaseapp.com',
    storageBucket: 'internspirit-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5d-m2HF_UGdCsHNYY_v6MMtJWkhciPng',
    appId: '1:755431663302:android:f68dfd4109f2b4d33559c7',
    messagingSenderId: '755431663302',
    projectId: 'internspirit-hackathon',
    storageBucket: 'internspirit-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCKyfJqX8npLT903FAfqpyZzThH_aOoKE',
    appId: '1:755431663302:ios:5c6bd68221db8cef3559c7',
    messagingSenderId: '755431663302',
    projectId: 'internspirit-hackathon',
    storageBucket: 'internspirit-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.internspiritHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCKyfJqX8npLT903FAfqpyZzThH_aOoKE',
    appId: '1:755431663302:ios:5c6bd68221db8cef3559c7',
    messagingSenderId: '755431663302',
    projectId: 'internspirit-hackathon',
    storageBucket: 'internspirit-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.internspiritHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWlZmdSGsScvxqKz6YHpi24nXBExCAHFw',
    appId: '1:755431663302:web:f6684736203186d13559c7',
    messagingSenderId: '755431663302',
    projectId: 'internspirit-hackathon',
    authDomain: 'internspirit-hackathon.firebaseapp.com',
    storageBucket: 'internspirit-hackathon.firebasestorage.app',
  );
}
