// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ADx51wll3XvYBlohvxDEyaS8CPYvYT0',
    appId: '1:327567577449:web:f12bbec78e1274268e2df8',
    messagingSenderId: '327567577449',
    projectId: 'demo2-d5fe2',
    authDomain: 'demo2-d5fe2.firebaseapp.com',
    storageBucket: 'demo2-d5fe2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GhaRkJA2VgsxdGXAw3uLAr2kltMJAO4',
    appId: '1:327567577449:android:434c45f7c8594be38e2df8',
    messagingSenderId: '327567577449',
    projectId: 'demo2-d5fe2',
    storageBucket: 'demo2-d5fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDix--fJZMzHuDGr2kQfG-9L8L5oPMymww',
    appId: '1:327567577449:ios:367eeb103564919c8e2df8',
    messagingSenderId: '327567577449',
    projectId: 'demo2-d5fe2',
    storageBucket: 'demo2-d5fe2.firebasestorage.app',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDix--fJZMzHuDGr2kQfG-9L8L5oPMymww',
    appId: '1:327567577449:ios:367eeb103564919c8e2df8',
    messagingSenderId: '327567577449',
    projectId: 'demo2-d5fe2',
    storageBucket: 'demo2-d5fe2.firebasestorage.app',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3ADx51wll3XvYBlohvxDEyaS8CPYvYT0',
    appId: '1:327567577449:web:6d968709865302cf8e2df8',
    messagingSenderId: '327567577449',
    projectId: 'demo2-d5fe2',
    authDomain: 'demo2-d5fe2.firebaseapp.com',
    storageBucket: 'demo2-d5fe2.firebasestorage.app',
  );
}
