// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNepfvq-k9PkO_cI6Kj21teKFnqnpiyg',
    appId: '1:387850705763:web:8b9a8a58406e3a9393d156',
    messagingSenderId: '387850705763',
    projectId: 'my-recipes-c0746',
    authDomain: 'my-recipes-c0746.firebaseapp.com',
    storageBucket: 'my-recipes-c0746.firebasestorage.app',
    measurementId: 'G-JNG9FX65WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhJ43mdnK18tfl7tXzS5_yAfSTSnNXAjE',
    appId: '1:387850705763:android:45307efb75d75eaf93d156',
    messagingSenderId: '387850705763',
    projectId: 'my-recipes-c0746',
    storageBucket: 'my-recipes-c0746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuDwgfysBddcakS2a5QACUJ9OjIq1aMsA',
    appId: '1:387850705763:ios:e93ee2fe16e2b7a193d156',
    messagingSenderId: '387850705763',
    projectId: 'my-recipes-c0746',
    storageBucket: 'my-recipes-c0746.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuDwgfysBddcakS2a5QACUJ9OjIq1aMsA',
    appId: '1:387850705763:ios:e93ee2fe16e2b7a193d156',
    messagingSenderId: '387850705763',
    projectId: 'my-recipes-c0746',
    storageBucket: 'my-recipes-c0746.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsNepfvq-k9PkO_cI6Kj21teKFnqnpiyg',
    appId: '1:387850705763:web:bfcd6b43cfe6d43993d156',
    messagingSenderId: '387850705763',
    projectId: 'my-recipes-c0746',
    authDomain: 'my-recipes-c0746.firebaseapp.com',
    storageBucket: 'my-recipes-c0746.firebasestorage.app',
    measurementId: 'G-NDH5L5BDPE',
  );
}
